[install]
is_configured = 1

[ui]
is_visible = 0
label = Asteron v3 Synthetic Ingest

[launcher]
author = OpenAI
version = 0.1.2
description = Parsing support for SILK SPECTER v3 synthetic HEC-envelope file ingestion.
