[asteron_easy]
homePath   = $SPLUNK_DB/asteron_easy/db
coldPath   = $SPLUNK_DB/asteron_easy/colddb
thawedPath = $SPLUNK_DB/asteron_easy/thaweddb

[asteron_medium]
homePath   = $SPLUNK_DB/asteron_medium/db
coldPath   = $SPLUNK_DB/asteron_medium/colddb
thawedPath = $SPLUNK_DB/asteron_medium/thaweddb

[asteron_hard]
homePath   = $SPLUNK_DB/asteron_hard/db
coldPath   = $SPLUNK_DB/asteron_hard/colddb
thawedPath = $SPLUNK_DB/asteron_hard/thaweddb
